name: Inject
description: Dependency Management with CommonJS and AMD Support
future: true
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  entity_output: symbolic
safe: true
pygments: true